/* Generated by tools/update.py from https://19hz.info/eventlisting_Miami.php */
window.UG_DATA = {
"updated": "2026-09-25",
"source": "https://19hz.info/eventlisting_Miami.php",
"events": [
{
"date": "2026-09-25",
"time": "7pm-10pm",
"title": "Expansion: Ecstatic Dance Miami",
"url": "https://shotgun.live/en/events/expansion",
"venue": "777 Northeast 79th Street",
"city": "Miami",
"tags": [],
"price": "free w/rsvp / $30",
"age": "",
"crew": ""
},
{
"date": "2026-09-25",
"time": "8pm",
"title": "Afrojack",
"url": "https://speakeasygo.com/event/EVE-HTGXEH",
"venue": "E11even",
"city": "Miami",
"tags": [
"big room house",
"electro house"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "",
"crew": ""
},
{
"date": "2026-09-25",
"time": "8pm-3am",
"title": "Breaks Yo! Kendall - Bebe Breaks, Endy, Tempoe, Xcessive Hypnotism",
"url": "https://www.facebook.com/events/1036750246060792/",
"venue": "Tacos And Tattoos",
"city": "Kendall",
"tags": [
"breaks"
],
"price": "",
"age": "",
"crew": ""
},
{
"date": "2026-09-25",
"time": "8pm-4am",
"title": "Aire (Miami): Opening Weekend w/ Gab Rhome",
"url": "https://posh.vip/e/gab-rhome-opening-weekend",
"venue": "Aire",
"city": "Miami",
"tags": [
"progressive house",
"tech house"
],
"price": "free w/rsvp b4 midnight ladies / $23",
"age": "",
"crew": ""
},
{
"date": "2026-09-25",
"time": "9pm-2am",
"title": "Dub X Mini Bar",
"url": "https://posh.vip/e/dub-x-mini-bar-13",
"venue": "Minibar",
"city": "Miami",
"tags": [
"house"
],
"price": "free w/rsvp b4 11pm / $12",
"age": "21+",
"crew": "Dub Miami"
},
{
"date": "2026-09-25",
"time": "9pm-3am",
"title": "Mary Zander / Thomas Sahs / Israel Sunshine",
"url": "https://shotgun.live/en/events/madradiomiami092526",
"venue": "Mad Radio",
"city": "Miami",
"tags": [
"tech house",
"deep house",
"progressive house"
],
"price": "Free w/RSVP b4 midnight ladies / $22",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "9pm-4am",
"title": "Koncrete Jungle Miami",
"url": "https://www.eventbrite.com/e/koncrete-jungle-miami-tickets-1999054960199",
"venue": "Hollywood Live Restaurant & Lounge",
"city": "Hollywood",
"tags": [
"drum and bass",
"jungle",
"miami bass",
"breaks",
"dubstep",
"bass music"
],
"price": "$5-10",
"age": "21+",
"crew": "Dubplates & Dragons"
},
{
"date": "2026-09-25",
"time": "10pm-3am",
"title": "Caiiro, Falyn",
"url": "https://dice.fm/event/mxyqxv-caiiro-falyn-25th-sep-sable-miami-miami-tickets",
"venue": "Sable",
"city": "Miami",
"tags": [
"afro house",
"tech house"
],
"price": "free w/rsvp b4 midnight / $30",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "10pm-3am",
"title": "DJ Sneak, Matt Flesher, Bandito Chico",
"url": "https://www.therumor.com/p/sneak",
"venue": "Lion's Den at Fooqs",
"city": "Miami",
"tags": [
"jackin house",
"deep house",
"funky house"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "10pm-3am",
"title": "Misifu, Fiin, Unor, Palma",
"url": "https://dice.fm/event/py3aey-lunasol-pres-misifu-25th-sep-lunasol-miami-tickets",
"venue": "Lunasol",
"city": "Miami",
"tags": [
"tech house",
"afro house",
"deep house",
"indie dance"
],
"price": "free w/rsvp b4 midnight / $24-36",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "10pm-4am",
"title": "Gravedgr",
"url": "https://dice.fm/event/ry8bwv-gravedgr-25th-sep-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"dubstep",
"trap"
],
"price": "$13.22",
"age": "18+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "10pm-4am",
"title": "New Blood + Transfusion",
"url": "https://shotgun.live/en/events/new-blood-transfusion",
"venue": "The Boombox",
"city": "Miami",
"tags": [
"hard techno",
"darkwave",
"trance",
"IDM",
"schranz",
"midtempo"
],
"price": "$15",
"age": "18+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "10pm-4am",
"title": "Somewhere Underground @ Nowhere | S5v3",
"url": "https://posh.vip/e/somewhere-underground-nowhere-s5v2-1",
"venue": "Nowhere Ftl",
"city": "Fort Lauderdale",
"tags": [
"house",
"EDM"
],
"price": "free w/rsvp b4 11pm / $10+",
"age": "21+",
"crew": "Nowhere Ftl"
},
{
"date": "2026-09-25",
"time": "10pm-4am",
"title": "Yoyaku: Satoshi Tomiie, Mari.Te",
"url": "https://dice.fm/event/927gy9-yoyaku-satoshi-tomiie-25th-sep-jolene-sound-room-miami-miami-tickets",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"techno",
"deep house"
],
"price": "$10",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "10pm-4am",
"title": "Zonaroza: Ft. Fantasia Royale Gaga w/DJ Cesar Romero",
"url": "https://shotgun.live/en/events/zona",
"venue": "777 Northeast 79th Street",
"city": "Miami",
"tags": [],
"price": "free-17.62",
"age": "18+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "10pm-5am",
"title": "Ctrl Room: Leandro Da Silva, Kallil, Leo Oliver",
"url": "https://ra.co/events/2530424",
"venue": "M2",
"city": "Miami",
"tags": [
"tech house"
],
"price": "free w/rsvp b4 midnight / $20",
"age": "21+",
"crew": "Pitchpark Events"
},
{
"date": "2026-09-25",
"time": "10pm-5am",
"title": "Eli Brown Panic Attack Tour",
"url": "https://fcty.tw/elibrown",
"venue": "Factory Town",
"city": "Miami",
"tags": [
"house",
"techno"
],
"price": "$50+",
"age": "18+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "10pm-5am",
"title": "Jim Rider",
"url": "https://dice.fm/event/dkoqlg-jim-rider-25th-sep-do-not-sit-on-the-furniture-miami-beach-tickets",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"progressive house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "10pm-7am",
"title": "Michaelbm, NSJ",
"url": "https://dice.fm/event/nvppyq-michaelbm-nsj-25th-sep-studio-60-miami-miami-tickets",
"venue": "Studio 60",
"city": "Miami",
"tags": [
"latin house",
"tech house",
"afro house"
],
"price": "$15",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "11pm-2pm",
"title": "BLOND:ISH, Yamagucci & Chinonegro",
"url": "https://dice.fm/event/3o78bl-blondish-yamagucci-chinonegro-25th-sep-club-space-miami-miami-tickets",
"venue": "Club Space",
"city": "Miami",
"tags": [
"progressive house",
"tech house",
"minimal"
],
"price": "$20+",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "11pm-5am",
"title": "Shonky, Jennifer Loveless",
"url": "https://dice.fm/event/yod8px-shonky-jennifer-loveless-25th-sep-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"tech house"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "11pm-5am",
"title": "Steve Aoki",
"url": "https://www.universe.com/events/PBTC9F",
"venue": "Liv Nightclub",
"city": "Miami",
"tags": [
"big room",
"trap",
"hip-hop",
"pop EDM"
],
"price": "$49.84-304.43",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "11pm-7am",
"title": "Autonomy: Sherelle, Bok Bok, & Introspekt",
"url": "https://link.dice.fm/autonomyground",
"venue": "The Ground At Club Space",
"city": "Miami",
"tags": [
"club music",
"garage",
"techno",
"house"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-25",
"time": "11:30pm-4am",
"title": "Sistek",
"url": "https://posh.vip/e/sistek-selva",
"venue": "Selva",
"city": "Miami",
"tags": [
"afro house"
],
"price": "$45+",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "10am-3am",
"title": "Roger Sanchez + Inbal",
"url": "https://dice.fm/event/3obpvx-roger-sanchez-inbal-26th-sep-sable-miami-miami-tickets",
"venue": "Sable",
"city": "Miami",
"tags": [
"soulful house",
"disco"
],
"price": "free w/rsvp b4 midnight / $30",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "12pm-7pm",
"title": "Landis",
"url": "https://www.tixr.com/groups/daerdayclubsouthflorida/events/saturday-september-26th-daer-dayclub-199438",
"venue": "Daer Dayclub",
"city": "Hollywood",
"tags": [],
"price": "free w/rsvp b4 2 / $37",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "4pm-10pm",
"title": "Loud Luxury",
"url": "https://posh.vip/e/loud-luxury-presented-by-palm-tree-club-miami-copy",
"venue": "Palm Tree Club",
"city": "Miami",
"tags": [
"pop EDM",
"tropical house",
"house",
"synthpop"
],
"price": "$75",
"age": "21+",
"crew": "Palm Tree Club Miami"
},
{
"date": "2026-09-26",
"time": "4pm-11pm",
"title": "Intriga Day Party Ft Santelises, Axatipe & More",
"url": "https://link.dice.fm/W5e44a3a81ef",
"venue": "Boho House",
"city": "Miami",
"tags": [
"afro house",
"progressive house",
"indie dance"
],
"price": "free b4 7pm / $35",
"age": "21+",
"crew": "Intriga Collective"
},
{
"date": "2026-09-26",
"time": "5pm-12am",
"title": "Safe Sound / A Return To Practice / Each Other: Diego Andres, Mutant Pete , Terence Tabeau, Extra Andrew, Artime, Lotusoph",
"url": "https://ra.co/events/2539103",
"venue": "Zoko Collective",
"city": "Miami",
"tags": [
"house"
],
"price": "free",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "8pm",
"title": "Riva Starr, Seamus Haji",
"url": "https://calendar.zeyzeymiami.com/shows/riva-starr-26-sep",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"deep house",
"tech house"
],
"price": "free w/rsvp",
"age": "21+",
"crew": "Nervous"
},
{
"date": "2026-09-26",
"time": "8pm",
"title": "Ruckus",
"url": "https://speakeasygo.com/event/EVE-0O8CYX",
"venue": "E11even",
"city": "Miami",
"tags": [
"big room",
"pop EDM"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "",
"crew": ""
},
{
"date": "2026-09-26",
"time": "8pm-12am",
"title": "Offaiah",
"url": "https://dice.fm/event/l8mlbl-upside-presents-offaiah-mindgazm-friends-26th-sep-upside-miami-tickets",
"venue": "Upside",
"city": "Miami",
"tags": [
"house"
],
"price": "free w/rsvp",
"age": "21+",
"crew": "Right Now Productions"
},
{
"date": "2026-09-26",
"time": "8pm-2am",
"title": "Riva Starr",
"url": "https://ra.co/events/2506139",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"deep house",
"tech house"
],
"price": "free w/rsvp",
"age": "",
"crew": "Nervous Records"
},
{
"date": "2026-09-26",
"time": "8pm-4am",
"title": "Aire (Miami): Pendulum By Steve Lawler, Ella Romand and Stefaina",
"url": "https://posh.vip/e/aire-miami-pendulum-with-steve-lawler-ella-romand-and-stefaina",
"venue": "Aire",
"city": "Miami",
"tags": [
"tech house",
"deep house",
"progressive house"
],
"price": "free w/rsvp b4 midnight ladies / $23",
"age": "",
"crew": ""
},
{
"date": "2026-09-26",
"time": "9pm-3am",
"title": "DJ Ray / Ez Dee",
"url": "https://shotgun.live/en/events/madradiomiami092626",
"venue": "Mad Radio",
"city": "Miami",
"tags": [
"house",
"electro",
"club music",
"acid"
],
"price": "free w/rsvp b4 midnight ladies / $22",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "10pm",
"title": "Rewind: 2000s Rave",
"url": "https://dice.fm/event/3obkrv-rewind-2000s-rave-26th-sep-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [],
"price": "$29+",
"age": "18+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "10pm-3am",
"title": "Madota, Manumat",
"url": "https://www.therumor.com/p/madota",
"venue": "Lion's Den at Fooqs",
"city": "Miami",
"tags": [
"progressive house",
"playa tech"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "10pm-3am",
"title": "Sebastien Leger, Conosur, and Terramuzik",
"url": "https://dice.fm/event/eo6p2w-sebastien-leger-conosur-and-terramuzik-26th-sep-lunasol-miami-tickets",
"venue": "Lunasol",
"city": "Miami",
"tags": [
"french house",
"tech house",
"techno"
],
"price": "$36+",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "10pm-4am",
"title": "Nick Warren",
"url": "https://dice.fm/event/v32736-nick-warren-26th-sep-jolene-sound-room-miami-miami-tickets",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"tech house",
"techno",
"deep house"
],
"price": "$10+",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "10pm-4am",
"title": "The World Is Yours Presents Brylin Vs The World",
"url": "https://posh.vip/e/the-wiggle-room-nowhere-special-event-1",
"venue": "Nowhere Ftl",
"city": "Fort Lauderdale",
"tags": [
"house",
"EDM"
],
"price": "$12+",
"age": "21+",
"crew": "Nowhere Ftl, The World Is Yours"
},
{
"date": "2026-09-26",
"time": "10pm-5am",
"title": "Daniel Orpi",
"url": "https://dice.fm/event/ww9mbp-daniel-orpi-26th-sep-edge-miami-miami-tickets",
"venue": "Edge",
"city": "Miami",
"tags": [
"tech house"
],
"price": "free w/rsvp ladies / free w/rsvp b4 midnight / $20+",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "10pm-5am",
"title": "Fisher",
"url": "https://dice.fm/event/avxpod-fisher-26th-sep-factory-town-miami-tickets",
"venue": "Factory Town",
"city": "Miami",
"tags": [
"tech house"
],
"price": "$125.5",
"age": "18+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "10pm-5am",
"title": "Flux Pavilion",
"url": "https://dice.fm/event/923ggd-flux-pavilion-special-guests-26th-sep-studio-60-miami-miami-tickets",
"venue": "Studio 60",
"city": "Miami",
"tags": [
"dubstep",
"drum and bass",
"electro house"
],
"price": "$25",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "10pm-5am",
"title": "Niki Sadeki",
"url": "https://dice.fm/event/q2pqqo-niki-sadeki-26th-sep-do-not-sit-on-the-furniture-miami-beach-tickets",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"tech house",
"progressive house",
"deep house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "10pm-5am",
"title": "Vladimir Dubyshkin, Grace Dahl",
"url": "https://dice.fm/event/bb97ro-vladimir-dubyshkin-grace-dahl-26th-sep-domicile-miami-miami-tickets",
"venue": "Domicile",
"city": "Miami",
"tags": [
"techno"
],
"price": "$20+",
"age": "18+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "11pm-2pm",
"title": "Franky Rizardo",
"url": "https://dice.fm/event/yod8nx-franky-rizardo-presents-flow-26th-sep-club-space-miami-miami-tickets",
"venue": "Club Space",
"city": "Miami",
"tags": [
"jackin house",
"funky house",
"deep house",
"tech house"
],
"price": "$30+",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "11pm-5am",
"title": "Crankdat",
"url": "https://www.universe.com/events/XF5VW9",
"venue": "Liv Nightclub",
"city": "Miami",
"tags": [
"trap"
],
"price": "$50+",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "11pm-5am",
"title": "My Friend Misty",
"url": "https://link.dice.fm/mfmseptember",
"venue": "Floyd",
"city": "Miami",
"tags": [
"tech house",
"minimal"
],
"price": "$10+",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-26",
"time": "11pm-5am",
"title": "Yaoi - The Rave Miami Fl X Hyperperreo",
"url": "https://shotgun.live/en/events/yaoi",
"venue": "777 Northeast 79th Street",
"city": "Miami",
"tags": [],
"price": "$17.62-22.03",
"age": "21+",
"crew": "Supernatural"
},
{
"date": "2026-09-27",
"time": "12pm-5pm",
"title": "Aurora Two",
"url": "https://shotgun.live/en/events/aurora-two",
"venue": "Baoshi Food Hall + Bar",
"city": "Pembroke Pines",
"tags": [
"tech house",
"deep house",
"afro house"
],
"price": "free",
"age": "",
"crew": ""
},
{
"date": "2026-09-27",
"time": "12pm-7pm",
"title": "Goodnight Johnboys Pool Party",
"url": "https://www.tixr.com/groups/daerdayclubsouthflorida/events/goodnight-johnboys-pool-party-daer-dayclub-199440",
"venue": "Daer Dayclub",
"city": "Hollywood",
"tags": [],
"price": "$20",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-27",
"time": "4pm-10pm",
"title": "Chillin N Grillin: Lou Flores, Demenz",
"url": "https://www.therumor.com/p/louf",
"venue": "Lion's Den at Fooqs",
"city": "Miami",
"tags": [
"techno",
"tech house"
],
"price": "",
"age": "",
"crew": ""
},
{
"date": "2026-09-27",
"time": "5pm-12am",
"title": "Breaks Yo! 8-Bit: Bebe Breaks, Masinc, Kharma, Ray Rex, Cosmictronic, Dwhite",
"url": "https://www.facebook.com/events/2663571360725366/",
"venue": "Tenth Level Tavern",
"city": "Oakland Park",
"tags": [
"breaks"
],
"price": "free",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-27",
"time": "8pm",
"title": "Damaged Goods",
"url": "https://speakeasygo.com/event/EVE-9WPK9L",
"venue": "E11even",
"city": "Miami",
"tags": [
"trap",
"hip-hop",
"EDM"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "",
"crew": ""
},
{
"date": "2026-09-27",
"time": "11pm-5am",
"title": "Knight Club : Spray, Cole Knight, Lucaz",
"url": "https://dice.fm/event/nvp3oq-knight-club-27th-sep-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"progressive house",
"tech house"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-28",
"time": "8pm",
"title": "Prankstisci",
"url": "https://speakeasygo.com/event/EVE-BDV3I4",
"venue": "E11even",
"city": "Miami",
"tags": [
"house",
"hip-hop",
"EDM"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "",
"crew": ""
},
{
"date": "2026-09-29",
"time": "8pm",
"title": "Yissel",
"url": "https://speakeasygo.com/event/EVE-X8TZD9",
"venue": "E11even",
"city": "Miami",
"tags": [
"house",
"hip-hop"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "",
"crew": ""
},
{
"date": "2026-09-30",
"time": "9pm-3am",
"title": "Undertone: Joaquin Bohmer",
"url": "https://shotgun.live/en/events/madradiomiami093026",
"venue": "Mad Radio",
"city": "Miami",
"tags": [
"house"
],
"price": "free",
"age": "21+",
"crew": ""
},
{
"date": "2026-09-30",
"time": "10pm-5am",
"title": "Jessy & Friends: Roland Clark, Louie Dager, Dall Ea, Elvi$ b2b Curly",
"url": "https://link.dice.fm/ac290c2482bd",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"house"
],
"price": "free w/rsvp b4 midnight ladies / $18-30",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-01",
"time": "10pm-4am",
"title": "Generous B",
"url": "https://dice.fm/event/6a8b4c2bfec44800018bccb4",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"house"
],
"price": "$7",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-02",
"time": "7pm-3am",
"title": "Blood Feast: V.Seven B2B Proletar, Hunter Steel B2B Icky, Dadrev, Domnrob, Cobb Douglas B2B Joey, Franky De Rey, Stinny Stone",
"url": "https://ra.co/events/2529889",
"venue": "Casa Nube Wynwood",
"city": "Miami",
"tags": [
"hard techno",
"trance"
],
"price": "$35+",
"age": "18+",
"crew": "Black Room"
},
{
"date": "2026-10-02",
"time": "8pm",
"title": "Flamingosis",
"url": "https://calendar.zeyzeymiami.com/shows/flamingosis-02-oct",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"funk",
"hip-hop",
"downtempo"
],
"price": "$24",
"age": "",
"crew": ""
},
{
"date": "2026-10-02",
"time": "8pm-4am",
"title": "Tim Green",
"url": "https://airemia.com/events/aire-presents-tim-green",
"venue": "Aire Miami",
"city": "Miami",
"tags": [
"progressive house",
"organic house",
"melodic house"
],
"price": "Free w/RSVP b4 midnight ladies / $23",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-02",
"time": "9pm-2am",
"title": "Trans*cendent x T4TWrestling",
"url": "https://ra.co/events/2534770",
"venue": "TBA",
"city": "Hollywood",
"tags": [
"trance",
"techno"
],
"price": "$23+",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-02",
"time": "10pm-4am",
"title": "Generous B: Dedro, Hakuna, Birds in Paradise",
"url": "https://dice.fm/event/bb9q7o-generous-b-presents-2nd-oct-jolene-sound-room-miami-miami-tickets",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"tech house",
"progressive house"
],
"price": "$7+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-02",
"time": "10pm-4am",
"title": "Joey Cash",
"url": "https://shotgun.live/en/events/joey-cash-the-boombox",
"venue": "The Boombox",
"city": "Miami",
"tags": [
"house"
],
"price": "$15-25",
"age": "",
"crew": ""
},
{
"date": "2026-10-02",
"time": "10pm-4am",
"title": "Planet Of The Drums",
"url": "https://dice.fm/event/q2dxea-planet-of-the-drums-2nd-oct-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"drum and bass"
],
"price": "$19.84",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-02",
"time": "10pm-5am",
"title": "Manifest By Amal Nemer",
"url": "https://shotgun.live/en/events/amal-nemer-manifest-oct-02",
"venue": "Edge",
"city": "Miami",
"tags": [
"tech house",
"latin house"
],
"price": "$17.62",
"age": "",
"crew": ""
},
{
"date": "2026-10-02",
"time": "10pm-5am",
"title": "Noise Mafia, Tabea, Mania",
"url": "https://dice.fm/event/53kd9k-noise-mafia-2nd-oct-domicile-miami-miami-tickets",
"venue": "Domicile",
"city": "Miami",
"tags": [
"hard techno",
"trance"
],
"price": "$20+",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-02",
"time": "10pm-5am",
"title": "Tal Fussman",
"url": "https://dice.fm/event/3or99l-tal-fussman-2nd-oct-do-not-sit-on-the-furniture-miami-beach-tickets",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"house",
"tech house",
"deep house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-02",
"time": "10pm-6am",
"title": "Andy Stott, Carrier, Uchi, Adam at the Door",
"url": "https://dice.fm/event/6dgdq3-andy-stott-carrier-2nd-oct-the-ground-miami-miami-tickets",
"venue": "The Ground",
"city": "Miami",
"tags": [
"techno",
"experimental",
"downtempo"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-02",
"time": "11pm-2pm",
"title": "Disco Dom, The Brothers Macklovitch",
"url": "https://dice.fm/event/6a91e895ea5f22000128b2ee",
"venue": "Club Space",
"city": "Miami",
"tags": [],
"price": "$30+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-02",
"time": "11pm-5am",
"title": "Lusid, Samantha Loveridge",
"url": "https://dice.fm/event/92n9l7-lusid-samantha-loveridge-2nd-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"progressive house"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-03",
"time": "12pm-7pm",
"title": "DJ Khaled",
"url": "https://www.tixr.com/groups/daerdayclubsouthflorida/events/dj-khaled-daer-dayclub-202003",
"venue": "Daer Dayclub",
"city": "Hollywood",
"tags": [
"hip-hop"
],
"price": "$40",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-03",
"time": "4pm-10pm",
"title": "Third Party",
"url": "https://posh.vip/e/third-party-presented-by-palm-tree-club-miami-copy",
"venue": "Palm Tree Club",
"city": "Miami",
"tags": [
"big room house",
"electro house",
"progressive house"
],
"price": "$20-50",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-03",
"time": "8pm-3am",
"title": "Ameme & Malive - Open Air",
"url": "https://shotgun.live/en/events/soundtuaryoctober3",
"venue": "Jungle Island",
"city": "Miami",
"tags": [
"afro house",
"tech house"
],
"price": "$28 b4 10 / $45+",
"age": "21+",
"crew": "Soundtuary"
},
{
"date": "2026-10-03",
"time": "9pm-6am",
"title": "Welker, Esse, Jkatz",
"url": "https://dice.fm/event/wwkwag-welker-esse-jkatz-3rd-oct-studio-60-miami-miami-tickets",
"venue": "Studio 60",
"city": "Miami",
"tags": [
"tech house",
"progressive house",
"indie dance"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-03",
"time": "10pm-3am",
"title": "Robag Wruhme",
"url": "https://dice.fm/event/k62kb9-robag-wruhme-jake-mercer-3rd-oct-sable-miami-miami-tickets",
"venue": "Sable",
"city": "Miami",
"tags": [
"house",
"techno"
],
"price": "free w/rsvp b4 midnight / $24",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-03",
"time": "10pm-4am",
"title": "Circuit - DJ Marfox",
"url": "https://shotgun.live/en/events/machina-records-presents-circuit",
"venue": "The Boombox",
"city": "Miami",
"tags": [
"afrobeats",
"afro house"
],
"price": "$15-20",
"age": "",
"crew": "Machina Records"
},
{
"date": "2026-10-03",
"time": "10pm-4am",
"title": "Lumasi",
"url": "https://dice.fm/event/yowqla-lumasi-3rd-oct-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"dubstep",
"bass music"
],
"price": "$13+",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-03",
"time": "10pm-4am",
"title": "Wata Igarashi",
"url": "https://dice.fm/event/xe3pkk-wata-igarashi-3rd-oct-jolene-sound-room-miami-miami-tickets",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"techno"
],
"price": "$12",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-03",
"time": "10pm-5am",
"title": "El Hormiguero: G. Segurola, Legend Saylor, Mambo, Sierra, Tomix, TRIIPEL",
"url": "https://bubbl.so/event/public/dFneCpJAtONjUTmAfs3Y",
"venue": "Edge",
"city": "Miami",
"tags": [
"tech house",
"minimal",
"electro"
],
"price": "",
"age": "",
"crew": ""
},
{
"date": "2026-10-03",
"time": "10pm-5am",
"title": "Tamir Regev, Jessy Nimni",
"url": "https://dice.fm/event/v3x88g-tamir-regev-3rd-oct-do-not-sit-on-the-furniture-miami-beach-tickets",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"prhg",
"tech house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-03",
"time": "11pm",
"title": "Whipped Cream",
"url": "https://calendar.zeyzeymiami.com/shows/whipped-cream-03-oct",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"bass music",
"trap",
"club music"
],
"price": "$25",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-03",
"time": "11pm-2pm",
"title": "Ame, Hardt Antoine",
"url": "https://dice.fm/event/6a91ebccea5f2200012d4c71",
"venue": "Club Space",
"city": "Miami",
"tags": [
"tech house"
],
"price": "$20+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-03",
"time": "11pm-5am",
"title": "Dublon",
"url": "https://dice.fm/event/eo87o2-dublon-3rd-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"dubstep",
"bass music"
],
"price": "$14.99",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-03",
"time": "11pm-7am",
"title": "Morgan Seatree, Datsko",
"url": "https://dice.fm/event/53mb5y-morgan-seatree-datsko-3rd-oct-the-ground-miami-miami-tickets",
"venue": "The Ground",
"city": "Miami",
"tags": [
"house"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-04",
"time": "8pm",
"title": "Livitup",
"url": "https://speakeasygo.com/event/EVE-AKBM9R",
"venue": "E11even",
"city": "Miami",
"tags": [
"house",
"nu-disco",
"hip-hop",
"latin"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "",
"crew": ""
},
{
"date": "2026-10-04",
"time": "11pm-5am",
"title": "Jay De Lys",
"url": "https://dice.fm/event/dk7l9o-jay-de-lys-4th-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"tech house",
"minimal",
"techno"
],
"price": "$10+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-05",
"time": "8pm",
"title": "A-Train",
"url": "https://speakeasygo.com/event/EVE-72H0QY",
"venue": "E11even",
"city": "Miami",
"tags": [
"pop EDM",
"big room",
"electro house",
"trap"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "",
"crew": ""
},
{
"date": "2026-10-06",
"time": "8pm",
"title": "Crespo",
"url": "https://speakeasygo.com/event/EVE-VFY4VP",
"venue": "E11even",
"city": "Miami",
"tags": [
"trap",
"dubstep",
"electro house",
"pop EDM"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "",
"crew": ""
},
{
"date": "2026-10-09",
"time": "3pm-9pm",
"title": "Luck Work",
"url": "https://www.tixr.com/groups/daerdayclubsouthflorida/events/luck-work-daer-dayclub-201835",
"venue": "Daer Dayclub",
"city": "Hollywood",
"tags": [],
"price": "$30-40",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "8pm-11:30pm",
"title": "Ultra Sunn The Beast In You Tour + Soft Vein",
"url": "https://uswpb.eventbrite.com/",
"venue": "Respectable Street",
"city": "West Palm Beach",
"tags": [
"coldwave",
"EBM",
"post-punk"
],
"price": "$25+",
"age": "18+",
"crew": "Heroes Live Entertainment"
},
{
"date": "2026-10-09",
"time": "9pm-1:30am",
"title": "Starjunk 95",
"url": "https://www.eventbrite.com/e/starjunk-95-midline-miami-tickets-1991307429125",
"venue": "Midline",
"city": "Miami",
"tags": [
"drum and bass",
"breaks",
"house"
],
"price": "$20.89-40.70",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "9pm-5am",
"title": "Dvs1",
"url": "https://dice.fm/event/v3l38d-dvs1-9th-oct-domicile-miami-miami-tickets",
"venue": "Domicile",
"city": "Miami",
"tags": [
"techno"
],
"price": "$22+",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "10pm-3am",
"title": "Solmates Season Opener Ft. Fahlberg, Orsay & More",
"url": "https://ra.co/events/2529443",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"progressive house"
],
"price": "$11.50 b4 11 / $12-57",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "10pm-4am",
"title": "Chase and Status",
"url": "https://www.tixr.com/groups/daernightclubsouthflorida/events/chase-and-status-daer-nightclub-202030",
"venue": "Daer Nightclub",
"city": "Hollywood",
"tags": [
"drum and bass"
],
"price": "$49+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "10pm-4am",
"title": "Chippy Nonstop, Pressure Point",
"url": "https://dice.fm/event/6aa83c59ff46e90001677da0",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"hard house",
"techno",
"trance"
],
"price": "$7 b4 12 / $10-12",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "10pm-4am",
"title": "Nifra",
"url": "https://dice.fm/event/6d83nq-nifra-9th-oct-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"big room trance",
"uplifting trance"
],
"price": "$13.22",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "10pm-5am",
"title": "Cosmic Gate",
"url": "https://dice.fm/event/6dolpq-eternal-frequencies-with-cosmic-gate-9th-oct-la-otra-miami-tickets",
"venue": "La Otra",
"city": "Miami",
"tags": [
"trance",
"progressive house",
"big room house"
],
"price": "$19.99",
"age": "21+",
"crew": "Apex"
},
{
"date": "2026-10-09",
"time": "10pm-5am",
"title": "Roots Of Bass - Bear Grillz, Usaybflow + More",
"url": "https://dice.fm/event/8eqn6w-roots-of-bass-bear-grillz-usaybflow-more-9th-oct-mad-live-miami-tickets",
"venue": "Mad Live",
"city": "Miami",
"tags": [
"dubstep",
"bass music",
"trap"
],
"price": "$19.99",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "10pm-5am",
"title": "Worship - Sub Focus / Dimension / Culture Shock / 1991",
"url": "https://dice.fm/partner/tickets/event/xeyxve-worship-sub-focusdimensionculture-shock1991-9th-oct-factory-town-miami-tickets",
"venue": "Factory Town",
"city": "Miami",
"tags": [
"drum and bass"
],
"price": "$50+",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "10pm-5am",
"title": "Yokoo",
"url": "https://dice.fm/event/6do778-yokoo-9th-oct-do-not-sit-on-the-furniture-miami-beach-tickets",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"progressive house",
"tech house",
"playa tech"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "10pm-6am",
"title": "Wuki",
"url": "https://dice.fm/event/2waxxp-wuki-9th-oct-studio-60-miami-miami-tickets",
"venue": "Studio 60",
"city": "Miami",
"tags": [
"house",
"dubstep",
"trap",
"EDM"
],
"price": "$21+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "11pm-2pm",
"title": "Mind Against, Max Meraki & Luch",
"url": "https://dice.fm/event/6a91ed7fa0dc520001417d57",
"venue": "Club Space",
"city": "Miami",
"tags": [
"minimal",
"techno",
"tech house"
],
"price": "$30",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "11pm-5am",
"title": "Alesso",
"url": "https://www.universe.com/events/Y9NL8Z",
"venue": "Liv Nightclub",
"city": "Miami",
"tags": [
"big room house",
"pop EDM"
],
"price": "$50+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-09",
"time": "11pm-5am",
"title": "Laolu, Karaba",
"url": "https://dice.fm/event/eonk26-laolu-karaba-9th-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"progressive house"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-10",
"time": "11am-2am",
"title": "MC4D",
"url": "https://www.eventbrite.com/e/mc4d-the-shorely-tickets-2000173734483",
"venue": "The Shorely At Marina Village",
"city": "Fort Lauderdale",
"tags": [
"pop EDM",
"country"
],
"price": "free",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-10",
"time": "12pm-7pm",
"title": "Gorgon City",
"url": "https://www.tixr.com/groups/daerdayclubsouthflorida/events/gorgon-city-daer-dayclub-202009",
"venue": "Daer Dayclub",
"city": "Hollywood",
"tags": [
"house"
],
"price": "$37",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-10",
"time": "4pm-10pm",
"title": "Benjamin Lloyd",
"url": "https://posh.vip/e/benjamin-lloyd-presented-by-palm-tree-club-miami-3",
"venue": "Palm Tree Club",
"city": "Miami",
"tags": [
"tech house"
],
"price": "free w/rsvp / $20-30",
"age": "21+",
"crew": "Palm Tree Club Miami"
},
{
"date": "2026-10-10",
"time": "9pm-3am",
"title": "Slow Life Showcase: Cecilio, Paolo Mosca",
"url": "https://ra.co/events/2517792",
"venue": "TBA",
"city": "Miami",
"tags": [
"house"
],
"price": "$11.50 pre",
"age": "21+",
"crew": "Trip Events, Explorer"
},
{
"date": "2026-10-10",
"time": "10pm-3am",
"title": "Sidequest",
"url": "https://wl.eventim.us/event/sidequest-midline-miami/704346?afflky=Midline",
"venue": "Midline",
"city": "Miami",
"tags": [
"house"
],
"price": "$33+",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-10",
"time": "10pm-4am",
"title": "Acraze",
"url": "https://www.tixr.com/groups/daernightclubsouthflorida/events/acraze-daer-nightclub-202031",
"venue": "Daer Nightclub",
"city": "Hollywood",
"tags": [
"tech house",
"big room techno"
],
"price": "$20",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-10",
"time": "10pm-4am",
"title": "Enamour",
"url": "https://dice.fm/event/eo6ewy-enamour-10th-oct-jolene-sound-room-miami-miami-tickets",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"progressive house",
"tech house"
],
"price": "$10",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-10",
"time": "10pm-4am",
"title": "Sodown",
"url": "https://dice.fm/event/bb95vm-so-down-10th-oct-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"dubstep",
"bass music"
],
"price": "$13.22",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-10",
"time": "10pm-5am",
"title": "Armin van Buuren",
"url": "https://dice.fm/event/8e96w5-armin-van-buuren-presents-the-orb-10th-oct-factory-town-miami-tickets",
"venue": "Factory Town",
"city": "Miami",
"tags": [
"trance",
"big room house"
],
"price": "$75",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-10",
"time": "10pm-5am",
"title": "Igor Marijuan",
"url": "https://dice.fm/event/v3x2xd-igor-marijuan-all-day-i-dream-10th-oct-do-not-sit-on-the-furniture-miami-beach-tickets",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"deep house",
"tech house",
"progressive house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-10",
"time": "11pm-2am",
"title": "Cannons DJ Set Afterparty",
"url": "https://ra.co/events/2525260",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"electropop"
],
"price": "$28.75-34.50",
"age": "18+",
"crew": "Zey Zey"
},
{
"date": "2026-10-10",
"time": "11pm-2pm",
"title": "Mason Collective",
"url": "https://dice.fm/event/7dx7bv-mvson-10th-oct-club-space-miami-miami-tickets",
"venue": "Club Space",
"city": "Miami",
"tags": [
"tech house"
],
"price": "$30",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-10",
"time": "11pm-5am",
"title": "Jackie Hollander",
"url": "https://dice.fm/event/oe9klm-jackie-hollander-10th-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"progressive house",
"tech house"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-10",
"time": "11pm-5am",
"title": "Sidepiece",
"url": "https://www.universe.com/events/BJ4M7D",
"venue": "Liv Nightclub",
"city": "Miami",
"tags": [
"tech house"
],
"price": "$50-304",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-11",
"time": "12pm-7pm",
"title": "Level Up",
"url": "https://www.tixr.com/groups/daerdayclubsouthflorida/events/level-up-daer-dayclub-202010",
"venue": "Daer Dayclub",
"city": "Hollywood",
"tags": [
"dubstep",
"riddim",
"bass music"
],
"price": "$37+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-11",
"time": "5pm-9pm",
"title": "Lukas & Frank",
"url": "https://ra.co/events/2513782",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"house",
"afro house"
],
"price": "$17.25-28.75",
"age": "21+",
"crew": "Happy Hour"
},
{
"date": "2026-10-11",
"time": "8pm",
"title": "Damaged Goods",
"url": "https://speakeasygo.com/event/EVE-5D8NCI",
"venue": "E11even",
"city": "Miami",
"tags": [
"trap",
"hip-hop",
"EDM"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "",
"crew": ""
},
{
"date": "2026-10-13",
"time": "6pm-10pm",
"title": "DJ Three, Peter Wohelski, Grumptronix",
"url": "https://dice.fm/event/eongl6-iii-points-dale-zine-present-trip-magazeen-miami-book-launch-13th-oct-dle-zine-miami-tickets",
"venue": "Dale Zine",
"city": "Miami",
"tags": [
"funky house",
"deep house"
],
"price": "free w/rsvp",
"age": "18+",
"crew": "III Points"
},
{
"date": "2026-10-14",
"time": "7pm-1am",
"title": "Neon Indian, Twin Shadow, Washed Out",
"url": "https://dice.fm/event/ww999v-satellite-neon-indian-dj-set-twin-shadow-washed-out-dj-set-14th-oct-zeyzey-miami-tickets",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"synthpop"
],
"price": "$30+",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-15",
"time": "3pm-1am",
"title": "Chasewest",
"url": "https://dice.fm/event/6dooo2-satellite-chasewest-b2b-discip-ragie-ban-dan-molinari-stixx-15th-oct-zeyzey-miami-tickets",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"tech house"
],
"price": "$37.75",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-15",
"time": "9pm-2am",
"title": "Taiki Nulight + Sir Spyro",
"url": "https://shotgun.live/en/events/ag-x-rumble-present-taiki-nulight-sir-spyro",
"venue": "1-800-Lucky",
"city": "Miami",
"tags": [
"drum and bass",
"dubstep",
"bass house",
"breaks"
],
"price": "free",
"age": "21+",
"crew": "American Grime X Rumble"
},
{
"date": "2026-10-15",
"time": "10pm-2am",
"title": "Moscoman, Red Axes, & Whitesquare",
"url": "https://dice.fm/event/mxn9kw-satellite-moscoman-red-axes-whitesquare-15th-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"electronic rock"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-15",
"time": "10pm-4am",
"title": "Shanti Celeste b2b Peach, Sister System b2b Gio Elia",
"url": "https://dice.fm/event/k65y9l-satellite-shanti-celeste-b2b-peach-15th-oct-jolene-sound-room-miami-miami-tickets",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"deep house",
"tech house",
"techno"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-15",
"time": "11pm-2pm",
"title": "Cloonee, Miluhska, Omar+, Vintage Culture",
"url": "https://dice.fm/event/pywnk8-satellite-cloonee-miluhska-omar-vintage-culture-15th-oct-club-space-miami-miami-tickets",
"venue": "Club Space",
"city": "Miami",
"tags": [
"tech house"
],
"price": "$50+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-15",
"time": "11pm-7am",
"title": "Flying Lotus (DJ Set), Actress, Ivy Lab",
"url": "https://dice.fm/event/dkdpev-satellite-flying-lotus-actress-ivy-lab-more-15th-oct-the-ground-miami-miami-tickets",
"venue": "The Ground",
"city": "Miami",
"tags": [
"future beats",
"glitch-hop",
"hip-hop",
"dubstep",
"bass music",
"drum and bass"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-16",
"time": "Fri: 3pm-Sun: 3am",
"title": "III Points 2026",
"url": "https://iiipoints.frontgatetickets.com/?utm_source=Promoters&utm_medium=19hz&utm_campaign=19hz",
"venue": "Mana Wynwood",
"city": "Miami",
"tags": [
"multigenre EDM"
],
"price": "All ages",
"age": "",
"crew": "Insomniac"
},
{
"date": "2026-10-16",
"time": "8pm",
"title": "Party Pupils",
"url": "https://calendar.zeyzeymiami.com/shows/party-pupils-16-oct",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"future funk",
"house"
],
"price": "$19",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-16",
"time": "10pm-4am",
"title": "Codd Dubz, He$h",
"url": "https://dice.fm/event/923lv9-codd-dubz-x-heh-16th-oct-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"dubstep",
"trap"
],
"price": "$20+",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-16",
"time": "10pm-4am",
"title": "Satellite: Special Guests",
"url": "https://dice.fm/event/6a823197b96d4a000112d8fb",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"TBD"
],
"price": "$10",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-16",
"time": "10pm-5am",
"title": "Chris Schwarzwalder",
"url": "https://dice.fm/event/6a85c26e21cf7000014e0781",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"tech house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-16",
"time": "10pm-8am",
"title": "The Pickle Grand Opening",
"url": "https://ra.co/events/2528904",
"venue": "1395 NW 57th Ave",
"city": "Miami",
"tags": [
"house",
"electro",
"techno"
],
"price": "$11.20-22.35",
"age": "",
"crew": ""
},
{
"date": "2026-10-16",
"time": "11pm-2pm",
"title": "999999999, KI/KI, Roman Flugel B2B Danny Daze, Yousuke Yukimatsu",
"url": "https://dice.fm/event/6a8724f65b367e0001f22de9",
"venue": "Club Space",
"city": "Miami",
"tags": [
"techno"
],
"price": "$30+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-16",
"time": "11pm-5am",
"title": "Odd Mob",
"url": "https://dice.fm/event/2wqyva-satellite-odd-mob-16th-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"house",
"progressive house"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-16",
"time": "11:30pm-5:30am",
"title": "Black Coffee",
"url": "https://www.livnightclub.com/miami/event/EVE112156200020261016/friday/?ref=raco",
"venue": "Liv Nightclub",
"city": "Miami",
"tags": [
"progressive house",
"organic house",
"afro house"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-17",
"time": "12pm-7pm",
"title": "Ian Asher",
"url": "https://www.tixr.com/groups/daerdayclubsouthflorida/events/saturday-october-17th-daer-dayclub-202011",
"venue": "Daer Dayclub",
"city": "Hollywood",
"tags": [
"EDM",
"house"
],
"price": "$37",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-17",
"time": "4pm-9pm",
"title": "Mose",
"url": "https://www.eventbrite.com/e/mose-midline-miami-tickets-1990525304770",
"venue": "Midline",
"city": "Miami",
"tags": [],
"price": "$51.27",
"age": "18+",
"crew": "BLNK CNVS"
},
{
"date": "2026-10-17",
"time": "9pm-3am",
"title": "Iliad, Earworm, Noforms, Sana, Ember, & Miss Purple Shampoo",
"url": "https://dice.fm/event/k62pqq-iii-points-satellite-iliad-earworm-noforms-sana-ember-miss-purple-shampoo-17th-oct-las-rosas-miami-tickets",
"venue": "Las Rosas",
"city": "Miami",
"tags": [],
"price": "free",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-17",
"time": "10pm-3am",
"title": "Chez Damier",
"url": "https://dice.fm/event/oe8anr-lunasol-pres-chez-damier-17th-oct-lunasol-miami-tickets",
"venue": "Lunasol",
"city": "Miami",
"tags": [
"deep house"
],
"price": "free w/rsvp",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-17",
"time": "10pm-4am",
"title": "Beltran",
"url": "https://dice.fm/event/923k5d-satellite-beltran-more-17th-oct-jolene-sound-room-miami-miami-tickets",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"tech house"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-17",
"time": "10pm-4am",
"title": "Ydg",
"url": "https://www.tixr.com/groups/daernightclubsouthflorida/events/ydg-daer-nightclub-202033",
"venue": "Daer Nightclub",
"city": "Hollywood",
"tags": [
"dubstep"
],
"price": "$37 pre",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-17",
"time": "10pm-5am",
"title": "Khen",
"url": "https://dice.fm/event/l8733p-khen-17th-oct-do-not-sit-on-the-furniture-miami-beach-tickets",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"progressive house",
"tech house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-17",
"time": "11pm",
"title": "Disco Lines, Four Tet b2b Floating Points b2b Daphni, Horsegiirl, Kettama",
"url": "https://dice.fm/event/6a8726aa69055f0001adb581",
"venue": "Club Space",
"city": "Miami",
"tags": [
"downtempo",
"jazz",
"leftfield",
"house"
],
"price": "$50+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-17",
"time": "11pm-5am",
"title": "Marsolo, Silvie Loto",
"url": "https://dice.fm/event/yodwr2-satellite-marsolo-silvie-loto-17th-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"house"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-17",
"time": "11pm-7am",
"title": "HAAi, Jacques Greene, & DJ Fuckoff",
"url": "https://dice.fm/event/3orxdp-satellite-haai-jacques-greene-dj-fuckoff-17th-oct-the-ground-miami-miami-tickets",
"venue": "The Ground",
"city": "Miami",
"tags": [
"techno"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-18",
"time": "3pm-11pm",
"title": "Satellite: Maccabi House at The Garden",
"url": "https://dice.fm/event/avxq2d-satellite-maccabi-house-at-the-garden-18th-oct-hialeah-park-casino-hialeah-tickets",
"venue": "Hialeah Park Casino",
"city": "Miami",
"tags": [],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-18",
"time": "8pm",
"title": "Mister Gray",
"url": "https://speakeasygo.com/event/EVE-DM2S9L",
"venue": "E11even",
"city": "Miami",
"tags": [
"house",
"pop"
],
"price": "free w/rsvp b4 1 / $23-34",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-18",
"time": "8pm",
"title": "tINI - Futttura World Tour",
"url": "https://www.ticketmaster.com/event/0D0064B3151133D8",
"venue": "Kaseya Center",
"city": "Miami",
"tags": [
"tech house",
"deep house"
],
"price": "",
"age": "",
"crew": ""
},
{
"date": "2026-10-18",
"time": "9pm-1am",
"title": "Frzzr, Disputer, Love, Janne, Bygone Summers, & Mono",
"url": "https://dice.fm/event/g58oy2-iii-points-satellite-frzzr-disputer-love-janne-bygone-summers-moo-18th-oct-las-rosas-miami-tickets",
"venue": "Las Rosas",
"city": "Miami",
"tags": [],
"price": "free",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-18",
"time": "10pm-4am",
"title": "Dean Turnley, KinAhau, & Dalva",
"url": "https://dice.fm/event/dkdpm6-satellite-dean-turnley-kinahau-dalva-18th-oct-jolene-sound-room-miami-miami-tickets",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"house",
"funk",
"hip-hop"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-18",
"time": "11pm-5am",
"title": "Saraga - Stardust",
"url": "https://dice.fm/event/923kq9-satellite-saraga-presents-stardust-18th-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-18",
"time": "11pm-7am",
"title": "1tbsp, DJ Chaotic Ugly, Safety Trance, TECH G1RLS",
"url": "https://dice.fm/event/oe8ax5-satellite-1tbsp-dj-chaotic-ugly-safety-trance-tech-g1rls-more-18th-oct-the-ground-miami-miami-tickets",
"venue": "The Ground",
"city": "Miami",
"tags": [
"indie dance",
"house"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-18",
"time": "Sun: 11pm-Tue: 8am",
"title": "Satellite: 33+ Hour III Points Closing Party",
"url": "https://dice.fm/event/k65ygl-satellite-33-hour-iii-points-closing-party-18th-oct-club-space-miami-miami-tickets",
"venue": "Club Space",
"city": "Miami",
"tags": [
"techno"
],
"price": "free",
"age": "21+",
"crew": "III Points"
},
{
"date": "2026-10-22",
"time": "7pm",
"title": "Mashbit",
"url": "https://calendar.zeyzeymiami.com/shows/mashbit-22-oct",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"progressive house",
"EDM"
],
"price": "$25",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-23",
"time": "8pm-11am",
"title": "Nicole Moudaber",
"url": "https://dice.fm/event/v3lpy7-nicole-moudaber-23rd-oct-club-space-miami-miami-tickets",
"venue": "Club Space",
"city": "Miami",
"tags": [
"techno",
"tech house"
],
"price": "$20+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-23",
"time": "10pm-3am",
"title": "Green Velvet + Cajmere (Vinyl Set)",
"url": "https://dice.fm/event/eonvo2-green-velvet-cajmere-vinyl-set-23rd-oct-sable-miami-miami-tickets",
"venue": "Sable",
"city": "Miami",
"tags": [
"tech house"
],
"price": "$60.62",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-23",
"time": "10pm-5am",
"title": "Basti Grub",
"url": "https://dice.fm/event/6a60e695f0b1670001ef63d2",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"deep house",
"tech house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-23",
"time": "11pm-5am",
"title": "Thunderpony's Saloon: Jack Marlow + Snooko",
"url": "https://dice.fm/event/l8mqew-thunderponys-saloon-jack-marlow-snooko-23rd-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"uk garage",
"house",
"bassline"
],
"price": "$10+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-23",
"time": "11pm-7am",
"title": "Baby J",
"url": "https://dice.fm/event/dkdr2g-baby-j-23rd-oct-the-ground-miami-miami-tickets",
"venue": "The Ground",
"city": "Miami",
"tags": [
"club",
"dubstep",
"breaks"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-24",
"time": "8pm",
"title": "EDX",
"url": "https://speakeasygo.com/event/EVE-W7S3OV",
"venue": "E11even",
"city": "Miami",
"tags": [
"progressive house",
"big room"
],
"price": "$23+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-24",
"time": "10pm-4am",
"title": "Doomsday Afterdark",
"url": "https://www.tixr.com/groups/daerdayclubsouthflorida/events/doomsday-daer-dayclub-afterdark-206563",
"venue": "Daer Dayclub",
"city": "Hollywood",
"tags": [],
"price": "$37",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-24",
"time": "10pm-4am",
"title": "Ida Engberg & Onyvaa",
"url": "https://dice.fm/event/l8m97w-ida-engberg-b2b-onyvaa-24th-oct-jolene-sound-room-miami-miami-tickets",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"techno"
],
"price": "$7 b4 12 / $10-12",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-24",
"time": "10pm-4am",
"title": "Kasia",
"url": "https://dice.fm/event/yodxp2-kasia-24th-oct-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"progressive house",
"trance"
],
"price": "$20+",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-24",
"time": "10pm-5am",
"title": "Paso Doble",
"url": "https://dice.fm/event/6a60e7f7170f000001347489",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"progressive house",
"tech house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-24",
"time": "11pm-2am",
"title": "Lewis Ofman",
"url": "https://ra.co/events/2534428",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"house",
"disco",
"funk"
],
"price": "$23-51.70",
"age": "18+",
"crew": "Zey Zey"
},
{
"date": "2026-10-24",
"time": "11pm-2pm",
"title": "Riordan, Luuk Van Dijk, Julian Fijma & James Poole",
"url": "https://dice.fm/event/6a91f30f69be3b0001c698fc",
"venue": "Club Space",
"city": "Miami",
"tags": [
"tech house"
],
"price": "$20+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-24",
"time": "11pm-4am",
"title": "Vavo",
"url": "https://www.tixr.com/groups/daernightclubsouthflorida/events/vavo-daer-nightclub-202036",
"venue": "Daer Nightclub",
"city": "Hollywood",
"tags": [
"pop EDM",
"trap",
"future bass"
],
"price": "$37+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-24",
"time": "11pm-5am",
"title": "Aluna",
"url": "https://dice.fm/event/6dg9r7-aluna-24th-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"house"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-24",
"time": "11:30pm",
"title": "Twinsick",
"url": "https://www.livnightclub.com/miami/event/EVE112156200020261024/saturday/?ref=ticketmaster",
"venue": "Liv",
"city": "Miami",
"tags": [
"tech house",
"pop EDM"
],
"price": "$62+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-25",
"time": "8pm",
"title": "Chizzle",
"url": "https://speakeasygo.com/event/EVE-KYZSSI",
"venue": "E11even",
"city": "Miami",
"tags": [
"pop EDM",
"electro house",
"trap",
"hip-hop"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-28",
"time": "8pm",
"title": "E11even Halloween Week Ft Renn Mateos",
"url": "https://speakeasygo.com/event/EVE-Y75L1E",
"venue": "E11even",
"city": "Miami",
"tags": [
"afro house",
"tech house",
"EDM"
],
"price": "free w/rsvp / $12-23",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-29",
"time": "8pm",
"title": "E11even Halloween Week Ft Damaged Goods",
"url": "https://speakeasygo.com/event/EVE-3L2NWY",
"venue": "E11even",
"city": "Miami",
"tags": [
"trap",
"hip-hop"
],
"price": "$23+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-29",
"time": "8:30pm",
"title": "Sunsquabi",
"url": "https://wl.eventim.us/event/sunsquabi/703607?afflky=FunkyBiscuit",
"venue": "The Funky Biscuit",
"city": "Boca Raton",
"tags": [
"electronic funk"
],
"price": "$32.14+",
"age": "21+",
"crew": "Afterlife Entertainment"
},
{
"date": "2026-10-29",
"time": "10pm-4am",
"title": "Hercules & Love Affair",
"url": "https://dice.fm/event/6a86066921cf70000141b5a6",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"disco",
"techno",
"tech house",
"deep house"
],
"price": "$10",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-30",
"time": "8pm-2am",
"title": "Hallorave",
"url": "https://posh.vip/e/hallowrave-1",
"venue": "TBA",
"city": "Miami",
"tags": [
"drum and bass",
"jungle",
"uk garage",
"uk bass"
],
"price": "$7+",
"age": "",
"crew": ""
},
{
"date": "2026-10-30",
"time": "10pm-4am",
"title": "Aline Umber b2b Krol",
"url": "https://dice.fm/event/6aa2fa7b8fd8d8000155bbf4",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"house",
"funk",
"live electronic"
],
"price": "$10+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-30",
"time": "10pm-5am",
"title": "Do Not Sit On Halloween ft. Mira",
"url": "https://dice.fm/event/6a85c487a9fab30001a240ed",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"progressive house",
"tech house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-30",
"time": "10pm-5am",
"title": "Lehar",
"url": "https://dice.fm/event/oe83ba-lehar-30th-oct-do-not-sit-on-the-furniture-miami-beach-tickets",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"progressive house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-30",
"time": "10pm-9am",
"title": "Free Acid Halloween Edition w/ Un_Mute",
"url": "https://ra.co/events/2527634",
"venue": "The Pickle",
"city": "Miami",
"tags": [
"house",
"electro",
"techno"
],
"price": "$16.80-27.95",
"age": "",
"crew": "The Pickle, Un_Mute Events"
},
{
"date": "2026-10-30",
"time": "Fri: 10pm-Sun: 7am",
"title": "Hocus Pocus 2026",
"url": "https://dice.fm/event/eoxxmw-hocus-pocus-2026-3-day-pass-30th-oct-factory-town-miami-tickets",
"venue": "Factory Town",
"city": "Miami",
"tags": [
"tech house",
"progressive house",
"techno",
"electro",
"breaks",
"uk garage",
"club",
"disco",
"drum and bass"
],
"price": "$190+",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-30",
"time": "11pm",
"title": "Fleetmac Wood + Horror Hifi",
"url": "https://calendar.zeyzeymiami.com/shows/fleetmac-wood-horror-hifi-free-entry-30-oct",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"disco",
"funk",
"remixes"
],
"price": "free w/rsvp b4 11pm / $35",
"age": "",
"crew": ""
},
{
"date": "2026-10-30",
"time": "11pm-2pm",
"title": "Halloweek: Camelphat & Volkoder",
"url": "https://dice.fm/event/6a91f44e3fb32f00016121ba",
"venue": "Club Space",
"city": "Miami",
"tags": [
"tech house",
"deep house",
"progressive house"
],
"price": "$30+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-30",
"time": "11pm-5am",
"title": "L.P. Rhythm + Salome Le Chat",
"url": "https://dice.fm/event/nvxye8-halloweek-lp-rhythm-salom-le-chat-30th-oct-floyd-miami-miami-tickets",
"venue": "Floyd Miami",
"city": "Miami",
"tags": [
"house"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-31",
"time": "4pm-10pm",
"title": "Blond:Ish",
"url": "https://posh.vip/e/blondish-presented-by-palm-tree-club-miami-copy",
"venue": "Palm Tree Club",
"city": "Miami",
"tags": [
"progressive house",
"tech house",
"minimal"
],
"price": "$60+",
"age": "21+",
"crew": "Palm Tree Club Miami"
},
{
"date": "2026-10-31",
"time": "6pm-2:30am",
"title": "Mark Farina's Mushroom Jazz - Halloween Edition w/ Nutritious",
"url": "https://calendar.zeyzeymiami.com/shows/mark-farina-s-mushroom-jazz-halloween-edition-31-oct",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"downtempo",
"hip-hop",
"beats"
],
"price": "free w/rsvp b4 11pm / $25+",
"age": "18+",
"crew": "Liquid Culture Records"
},
{
"date": "2026-10-31",
"time": "7pm-12am",
"title": "Daft Disko Halloween",
"url": "https://ra.co/events/2537063",
"venue": "Edge",
"city": "Miami",
"tags": [
"funky house",
"nu-disco",
"french touch"
],
"price": "$23",
"age": "21+",
"crew": "Orlove Entertainment"
},
{
"date": "2026-10-31",
"time": "8pm",
"title": "DJ Diesel",
"url": "https://speakeasygo.com/event/EVE-1IN495",
"venue": "E11even",
"city": "Miami",
"tags": [
"dubstep",
"trap"
],
"price": "$55+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-31",
"time": "9pm-4am",
"title": "Nights In Necropolis Presents: Necrodanse Halloween Party",
"url": "https://shotgun.live/en/events/nights-in-necropolis-presents-necrodanse-halloween-party",
"venue": "Churchill's Pub",
"city": "Miami",
"tags": [
"darkwave",
"post-punk",
"goth",
"EBM"
],
"price": "$15",
"age": "18+",
"crew": ""
},
{
"date": "2026-10-31",
"time": "10pm-2am",
"title": "DJ Habibeats",
"url": "https://www.eventbrite.com/e/dj-habibeats-midline-miami-tickets-1992170698186",
"venue": "Midline",
"city": "Miami",
"tags": [
"house"
],
"price": "$27.5-47.32",
"age": "21+",
"crew": "BLNK CNVS"
},
{
"date": "2026-10-31",
"time": "10pm-4am",
"title": "Laszewo",
"url": "https://www.tixr.com/groups/daernightclubsouthflorida/events/-aszewo-halloween-daer-nightclub-204542",
"venue": "Daer Nightclub",
"city": "Hollywood",
"tags": [
"synthpop",
"house",
"pop EDM"
],
"price": "$37",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-31",
"time": "10pm-5am",
"title": "Lehar, Lucas Zarate",
"url": "https://link.dice.fm/v2d48dbf0fc6",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"progressive house",
"tech house"
],
"price": "$24",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-31",
"time": "11pm-10am",
"title": "Area 94: Onur Ozer, Reptant, Max Kraushaar, Mastrapa",
"url": "https://dice.fm/event/xeg79e-area-94-onur-zer-by-unmute-31st-oct-94th-aero-squadron-miami-tickets",
"venue": "94th Aero Squadron",
"city": "Miami",
"tags": [
"tech house",
"progressive house",
"deep house"
],
"price": "$12.12",
"age": "18+",
"crew": "Un_Mute"
},
{
"date": "2026-10-31",
"time": "11pm-5am",
"title": "Faster Horses + Kyle Starkey",
"url": "https://link.dice.fm/floydhalloweek-sat",
"venue": "Floyd",
"city": "Miami",
"tags": [
"house",
"trance"
],
"price": "$20+",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-31",
"time": "11pm-5am",
"title": "Lehar",
"url": "https://dice.fm/event/6a96059fe78018000131b24b",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"progressive house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-10-31",
"time": "11:30pm",
"title": "Lost Frequencies",
"url": "https://www.livnightclub.com/miami/event/EVE112156200020261031/halloween-weekend/?ref=ticketmaster",
"venue": "Liv Nightclub",
"city": "Miami",
"tags": [
"indie dance",
"synthpop"
],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-01",
"time": "8pm",
"title": "Mister Gray",
"url": "https://speakeasygo.com/event/EVE-I4IZPG",
"venue": "E11even",
"city": "Miami",
"tags": [
"house",
"pop"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-01",
"time": "11pm-2pm",
"title": "Dixon B2B Jimi Jules & Whomadewho",
"url": "https://dice.fm/event/6a91f7bca0dc520001e02d08",
"venue": "Club Space",
"city": "Miami",
"tags": [
"tech house",
"deep house",
"techno"
],
"price": "$30+",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-03",
"time": "8pm",
"title": "Iron Lyon",
"url": "https://speakeasygo.com/event/EVE-Q31X6R",
"venue": "E11even",
"city": "Miami",
"tags": [
"trap",
"hip-hop",
"r&b",
"pop house"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-05",
"time": "7pm",
"title": "The Floozies",
"url": "https://calendar.zeyzeymiami.com/shows/the-floozies-05-nov",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"funk",
"synthpop",
"electropop"
],
"price": "$29+",
"age": "",
"crew": ""
},
{
"date": "2026-11-05",
"time": "8pm",
"title": "Grant Fisher",
"url": "https://speakeasygo.com/event/EVE-QEMJI1",
"venue": "E11even",
"city": "Miami",
"tags": [],
"price": "$23+",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-06",
"time": "8pm",
"title": "Amtrac",
"url": "https://app.opendate.io/e/amtrac-live-november-06-2026-708055?utm_source=bandsintown&click_id=Jx1LBob5Tp2MIMBGRqHHNg",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"house"
],
"price": "$29+",
"age": "18+",
"crew": ""
},
{
"date": "2026-11-06",
"time": "9pm",
"title": "Com Truise",
"url": "https://calendar.zeyzeymiami.com/shows/com-truise-06-nov",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"synthpop",
"downtempo",
"electro",
"IDM"
],
"price": "$29",
"age": "",
"crew": ""
},
{
"date": "2026-11-06",
"time": "10pm-5am",
"title": "Nico Morano",
"url": "https://dice.fm/event/6aa566da6b039600012eb306",
"venue": "Do Not Sit On The Furniture",
"city": "Miami Beach",
"tags": [
"progressive house",
"tech house"
],
"price": "$24.25",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-08",
"time": "7pm-12am",
"title": "Parra For Cuva",
"url": "https://shotgun.live/en/events/zeyzey-presents-parra-for-cuva",
"venue": "Zeyzey",
"city": "Miami",
"tags": [
"downtempo",
"tech house"
],
"price": "",
"age": "18+",
"crew": ""
},
{
"date": "2026-11-11",
"time": "6pm",
"title": "Lenny Pearce",
"url": "https://www.livenation.com/event/vvG1VZ_GwKcMx1/lenny-pearce-toddler-rave-world-tour",
"venue": "Ftl War Memorial Auditorium",
"city": "Fort Lauderdale",
"tags": [
"house",
"big room",
"pop EDM"
],
"price": "",
"age": "",
"crew": ""
},
{
"date": "2026-11-13",
"time": "10pm-4am",
"title": "Adiel, Yu Su",
"url": "https://dice.fm/event/6a85fc0f21cf70000116039a",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"house"
],
"price": "$10+",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-13",
"time": "10pm-5am",
"title": "Unreal",
"url": "https://dice.fm/event/6a84879f8e0c81000177fc08",
"venue": "Factory Town",
"city": "Miami",
"tags": [
"techno"
],
"price": "$49.99",
"age": "18+",
"crew": ""
},
{
"date": "2026-11-13",
"time": "11pm-7am",
"title": "Notion",
"url": "https://dice.fm/event/2wqn27-notion-13th-nov-the-ground-miami-miami-tickets",
"venue": "The Ground",
"city": "Miami",
"tags": [
"uk garage",
"drum and bass",
"bassline"
],
"price": "$15+",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-14",
"time": "2pm-8pm",
"title": "Sacred Meadows Art and Music Project",
"url": "https://sacredmeadowsfest.com/",
"venue": "Sawgrass Recreation Park",
"city": "Broward County",
"tags": [
"dubstep",
"bass music"
],
"price": "$59+",
"age": "",
"crew": ""
},
{
"date": "2026-11-14",
"time": "10pm-4am",
"title": "Jessica Audiffred",
"url": "https://dice.fm/event/7dwvg7-jessica-audiffred-14th-nov-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"bass house",
"future bass",
"dubstep"
],
"price": "$33+",
"age": "18+",
"crew": "Insomniac"
},
{
"date": "2026-11-14",
"time": "10pm-5am",
"title": "Odesza, Boys Noize, Bob Moses",
"url": "https://dice.fm/event/6a3077721b98d10001598c8a",
"venue": "Factory Town",
"city": "Miami",
"tags": [
"synthpop",
"future bass",
"house"
],
"price": "$80+",
"age": "18+",
"crew": ""
},
{
"date": "2026-11-15",
"time": "12pm-5pm",
"title": "Pier Pressure | Homecoming Weekend Finale",
"url": "https://posh.vip/e/pier-pressure-homecoming-weekend-finale",
"venue": "TBA",
"city": "Miami",
"tags": [],
"price": "",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-15",
"time": "8pm",
"title": "Damaged Goods",
"url": "https://speakeasygo.com/event/EVE-VKVBQV",
"venue": "E11even",
"city": "Miami",
"tags": [
"trap",
"hip-hop"
],
"price": "free w/rsvp b4 midnight / $23-34",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-16",
"time": "8pm",
"title": "George Clanton",
"url": "https://www.ticketweb.com/event/id/14992723",
"venue": "Las Rosas",
"city": "Miami",
"tags": [
"synthpop",
"chillwave"
],
"price": "$42+",
"age": "18+",
"crew": "Breakeven Booking"
},
{
"date": "2026-11-20",
"time": "8pm",
"title": "John Summit",
"url": "https://www.ticketmaster.com/event/0D0064B2B883819E",
"venue": "Kaseya Center",
"city": "Miami",
"tags": [
"tech house"
],
"price": "$252+",
"age": "",
"crew": ""
},
{
"date": "2026-11-20",
"time": "10pm-5am",
"title": "Darude - Hype Tour",
"url": "https://posh.vip/e/darude-hype-tour",
"venue": "La Otra At Mad Wynwood",
"city": "Miami",
"tags": [
"trance",
"progressive house"
],
"price": "$20+",
"age": "",
"crew": "Apex"
},
{
"date": "2026-11-21",
"time": "8pm",
"title": "John Summit",
"url": "https://www.ticketmaster.com/event/0D0064B3A9E1800A",
"venue": "Kaseya Center",
"city": "Miami",
"tags": [
"tech house"
],
"price": "$252+",
"age": "",
"crew": ""
},
{
"date": "2026-11-21",
"time": "10pm-4am",
"title": "Star Monster",
"url": "https://dice.fm/event/v3xw57-star-monster-21st-nov-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"dubstep",
"trap"
],
"price": "$13.22",
"age": "18+",
"crew": ""
},
{
"date": "2026-11-28",
"time": "10pm-3am",
"title": "Wonkywilla",
"url": "https://www.eventbrite.com/e/wonkywilla-midline-miami-tickets-1991488953068",
"venue": "Midline",
"city": "Miami",
"tags": [
"dubstep",
"bass music"
],
"price": "$20.89-47.32",
"age": "18+",
"crew": ""
},
{
"date": "2026-11-28",
"time": "10pm-4am",
"title": "Helena Hauff",
"url": "https://dice.fm/event/l87pxx-helena-hauff-28th-nov-jolene-sound-room-miami-miami-tickets",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"techno",
"electro"
],
"price": "$7+",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-28",
"time": "10pm-4am",
"title": "Ryan Elliot",
"url": "https://dice.fm/event/6do6o7-ryan-elliot-danny-daze-28th-nov-jolene-sound-room-miami-miami-tickets",
"venue": "Jolene Downtown",
"city": "Miami",
"tags": [
"house"
],
"price": "$10",
"age": "21+",
"crew": ""
},
{
"date": "2026-11-28",
"time": "10pm-4am",
"title": "Space Wizard",
"url": "https://dice.fm/event/xe3wmk-space-wizard-28th-nov-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"dubstep",
"bass music"
],
"price": "$13.22",
"age": "18+",
"crew": ""
},
{
"date": "2026-11-28",
"time": "11pm",
"title": "Bag Raiders",
"url": "https://dice.fm/event/53kwqd-bag-raiders-28th-nov-floyd-miami-miami-tickets",
"venue": "Floyd",
"city": "Miami",
"tags": [
"pop EDM",
"synthpop"
],
"price": "$10+",
"age": "21+",
"crew": ""
},
{
"date": "2026-12-03",
"time": "10pm",
"title": "Guy J",
"url": "https://dice.fm/event/k65y3q-guy-j-art-basel-3rd-dec-la-otra-miami-tickets",
"venue": "La Otra",
"city": "Miami",
"tags": [
"tech house",
"progressive house"
],
"price": "$36+",
"age": "21+",
"crew": "Apex"
},
{
"date": "2026-12-03",
"time": "10pm-4am",
"title": "Level Up",
"url": "https://dice.fm/event/92k2p7-level-up-cyclops-cove-pre-party-3rd-dec-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"dubstep",
"riddim",
"bass music"
],
"price": "$26.45",
"age": "18+",
"crew": "Insomniac"
},
{
"date": "2026-12-04",
"time": "4pm",
"title": "Anotr",
"url": "https://dice.fm/partner/tickets/event/2wqeoa-unkommon-events-framework-present-anotr-4th-dec-watson-island-park-miami-beach-tickets",
"venue": "Watson Island Park",
"city": "Miami Beach",
"tags": [
"tech house"
],
"price": "$115+",
"age": "21+",
"crew": "Unkommon Events & Framework"
},
{
"date": "2026-12-04",
"time": "8pm-3am",
"title": "Bedouin",
"url": "https://dice.fm/event/oe8nb5-bedouin-presents-saga-miami-art-week-2026-4th-dec-little-river-studios-miami-tickets",
"venue": "Little River Studios",
"city": "Miami",
"tags": [
"progressive house",
"tech house",
"deep house"
],
"price": "$60",
"age": "21+",
"crew": ""
},
{
"date": "2026-12-13",
"time": "6pm-12am",
"title": "Eelke Kleijn",
"url": "https://dice.fm/event/8e78rv-eelke-kliejn-live-13th-dec-upside-miami-tickets",
"venue": "Upside",
"city": "Miami",
"tags": [
"deep house",
"progressive house"
],
"price": "free b4 8pm / $20",
"age": "21+",
"crew": "Apex"
},
{
"date": "2026-12-26",
"time": "10pm-4am",
"title": "Avello",
"url": "https://dice.fm/event/53m9ew-avello-26th-dec-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"dubstep",
"bass music"
],
"price": "$39.67",
"age": "18+",
"crew": ""
},
{
"date": "2026-12-31",
"time": "9pm",
"title": "Dreamland 2026 Main Event",
"url": "https://www.tixr.com/groups/dreamlandnye/events/dreamland-new-years-festival-170476",
"venue": "Midline",
"city": "Miami",
"tags": [
"house",
"EDM"
],
"price": "$150+",
"age": "",
"crew": ""
},
{
"date": "2027-01-01",
"time": "9pm",
"title": "Dreamland 2026 - Meat | The Playlist",
"url": "https://www.tixr.com/groups/dreamlandnye/events/dreamland-new-years-festival-170476",
"venue": "M2",
"city": "Miami",
"tags": [
"house",
"EDM"
],
"price": "$150+",
"age": "",
"crew": ""
},
{
"date": "2027-01-02",
"time": "7pm",
"title": "Dreamland 2026 - The Oasis",
"url": "https://www.tixr.com/groups/dreamlandnye/events/dreamland-new-years-festival-170476",
"venue": "Throw Social",
"city": "Miami",
"tags": [
"house",
"EDM"
],
"price": "$150+",
"age": "",
"crew": ""
},
{
"date": "2027-01-03",
"time": "6pm-12am",
"title": "Jody Wisternoff",
"url": "https://posh.vip/e/jody-wisternoff-2",
"venue": "Upside",
"city": "Miami",
"tags": [
"progressive house",
"deep house"
],
"price": "free b4 8pm / $23",
"age": "",
"crew": "Apex"
},
{
"date": "2027-01-22",
"time": "10pm-4am",
"title": "Hamro",
"url": "https://dice.fm/event/py3lmy-hamro-22nd-jan-kemistry-fort-lauderdale-tickets",
"venue": "Kemistry",
"city": "Fort Lauderdale",
"tags": [
"dubstep",
"bass music"
],
"price": "$13.22",
"age": "18+",
"crew": ""
},
{
"date": "2027-01-29",
"time": "10pm-3am",
"title": "Heyz",
"url": "https://wl.eventim.us/event/heyz-midline-miami/704806?afflky=Midline",
"venue": "Midline",
"city": "Miami",
"tags": [
"dubstep",
"bass music",
"trap"
],
"price": "free w/rsvp b4 11pm 21+ / $28",
"age": "18+",
"crew": ""
},
{
"date": "2027-03-12",
"time": "7:30pm",
"title": "VNV Nation",
"url": "https://www.ticketmaster.com/event/0D00634ED44B687E",
"venue": "Culture Room",
"city": "Fort Lauderdale",
"tags": [
"synthpop",
"trance",
"EBM"
],
"price": "$50",
"age": "",
"crew": ""
}
],
"recurring": [
{
"when": "Mondays",
"time": "10pm-4am",
"title": "Electronic Hideout",
"url": "https://www.instagram.com/electronichideout",
"venue": "Ebar13",
"city": "Fort Lauderdale",
"tags": [
"tech house",
"progressive house",
"melodic techno",
"breaks",
"drum and bass",
"EDM"
],
"price": "Free",
"age": ""
},
{
"when": "Tuesdays",
"time": "8pm-12am",
"title": "Synth Battle",
"url": "https://www.eventbrite.com/o/gramps-19822380116",
"venue": "Gramps",
"city": "Miami",
"tags": [
"live electronic",
"open jam"
],
"price": "Free",
"age": ""
},
{
"when": "Tuesdays",
"time": "9pm-2am",
"title": "Rum & Bass",
"url": "https://www.instagram.com/rumandbass/",
"venue": "Coyo Taco",
"city": "Miami",
"tags": [
"reggae",
"dancehall",
"afrobeats",
"soca",
"EDM"
],
"price": "Free",
"age": ""
},
{
"when": "Tuesdays",
"time": "11pm-5am",
"title": "House Party Tuesdays",
"url": "https://www.facebook.com/events/925823038714634/",
"venue": "Twist",
"city": "Miami Beach",
"tags": [],
"price": "",
"age": "21+"
},
{
"when": "Wednesdays",
"time": "7pm-11pm",
"title": "Vinyl Time",
"url": "https://www.eventbrite.com/o/gramps-19822380116",
"venue": "Gramps",
"city": "Miami",
"tags": [
"open decks"
],
"price": "Free",
"age": ""
},
{
"when": "Fridays",
"time": "10pm",
"title": "Haus of Hyde",
"url": "https://www.sbe.com/nightlife/hyde/hyde-beach",
"venue": "Hyde Beach",
"city": "Miami Beach",
"tags": [
"house"
],
"price": "$30",
"age": "21+"
},
{
"when": "Saturdays",
"time": "10pm",
"title": "Proper Etiquette",
"url": "https://posh.vip/g/events-by-proper-etiquette",
"venue": "The Hub",
"city": "Fort Lauderdale",
"tags": [
"house"
],
"price": "Free",
"age": "21+"
},
{
"when": "2nd Saturdays",
"time": "10pm-4am",
"title": "United D&B and Friends",
"url": "https://www.instagram.com/p/CmuVUYhuEf0/",
"venue": "Kill Your Idol",
"city": "",
"tags": [
"dnb",
"jungle"
],
"price": "Free",
"age": "21+"
}
],
"venues": {
"1306 Miami": {
"url": "https://www.facebook.com/1306Miami/",
"address": "1306 N Miami Ave, Miami"
},
"1310 Gallery": {
"url": "https://www.facebook.com/1310Gallery/",
"address": "1310 SW 2nd Ct, Fort Lauderdale"
},
"Basement Miami": {
"url": "https://www.facebook.com/BasementMiami/events",
"address": "2901 Collins Ave, Miami Beach"
},
"Cameo Nightclub": {
"url": "https://www.facebook.com/Cameo.Nightclub.Miami/",
"address": "1445 Washington Ave, Miami Beach"
},
"Cash Only Bar": {
"url": "https://www.facebook.com/CashOnlyFTL/events",
"address": "15 West Las Olas Blvd, Fort Lauderdale"
},
"Catalina Hotel and Beach Club": {
"url": "https://www.facebook.com/catalinahotel/",
"address": "1720-1756 Collins Ave, Miami Beach"
},
"Chisme": {
"url": "https://www.instagram.com/chismemiamibeach/",
"address": "801 Collins Ave, Miami Beach"
},
"Clevelander": {
"url": "https://www.facebook.com/Clevelander/",
"address": "1020 Ocean Dr, Miami Beach"
},
"Club Space": {
"url": "https://www.facebook.com/ClubSpace/",
"address": "34 NE 11th St, Miami"
},
"Coyo Taco": {
"url": "https://www.facebook.com/coyotacowynwood/",
"address": "2300 NW 2nd Ave, Miami"
},
"DAER South Florida": {
"url": "https://www.facebook.com/daersouthflorida/",
"address": "1 Seminole Way, Fort Lauderdale"
},
"Do Not Sit On The Furniture": {
"url": "https://dice.fm/venue/do-not-sit-on-the-furniture-ovk5",
"address": "423 16th St, Miami Beach"
},
"Domicile": {
"url": "https://www.instagram.com/domicile.miami/",
"address": "6391 NW 2nd Ave, Miami"
},
"E11EVEN Miami": {
"url": "https://www.facebook.com/11Miami/events",
"address": "29 NE 11th St, Miami"
},
"Factory Town": {
"url": "https://www.factorytown.com/",
"address": "4800 NW 37th Ave, Miami"
},
"Floyd": {
"url": "https://www.facebook.com/floydmiami/",
"address": "34 NE 11th St, Miami"
},
"Foxhole": {
"url": "https://dice.fm/venue/foxhole-3oorg",
"address": "1218 14th Ct, Miami Beach"
},
"Freehand Miami": {
"url": "https://www.facebook.com/freehandmiami/",
"address": "2727 Indian Creek Dr, Miami Beach"
},
"FTX Arena": {
"url": "https://www.facebook.com/FTXArena/",
"address": "601 Biscayne Blvd, Miami"
},
"Gramps": {
"url": "https://www.facebook.com/grampsmiami/",
"address": "176 NW 24th ST, Miami"
},
"Insideout": {
"url": "https://www.facebook.com/itsinsideoutmiami/",
"address": "337 SW 8th St, Miami"
},
"Jolene Sound Room": {
"url": "https://www.jolenesoundroom.com/",
"address": "200 E Flagler St, Miami"
},
"Kill Your Idol": {
"url": "https://www.facebook.com/killyouridolmiami/events",
"address": "222 Espanola Way, Miami Beach"
},
"Klub Kutters": {
"url": "https://www.facebook.com/KlubKutters/",
"address": "215 SW 27th Ave, Fort Lauderdale"
},
"Lemon City Studios": {
"url": "https://www.facebook.com/LemonCityStudios/",
"address": "261 NE 73rd St, Miami"
},
"LIV Miami": {
"url": "https://www.facebook.com/LIVMiami/events",
"address": "4441 Collins Ave, Miami Beach"
},
"M2": {
"url": "https://www.tixr.com/groups/m2miami",
"address": "1235 Washington Ave, Miami Beach"
},
"Mana Wynwood": {
"url": "https://www.facebook.com/ManaWynwood/",
"address": "318 NW 23rd St, Miami"
},
"McSorley's Beach Pub": {
"url": "https://www.facebook.com/McSorleysFTL/events",
"address": "837 N Fort Lauderdale Beach Blvd, Fort Lauderdale"
},
"Mecasa Muzik": {
"url": "https://www.facebook.com/MeCasaMuzik/",
"address": "2127 NW 1st Ave, Miami"
},
"Mode": {
"url": "https://dice.fm/venue/mode-8q6w",
"address": "2 S Miami Ave, Miami"
},
"Munchie's Pizza Club": {
"url": "https://www.eventbrite.com/o/munchies-pizza-club-54515051693",
"address": "200 SW 2nd St, Fort Lauderdale"
},
"Mynt Lounge": {
"url": "https://www.facebook.com/MyntLoungeUSA/",
"address": "1921 Collins Ave, Miami Beach"
},
"Nikki Beach": {
"url": "https://www.facebook.com/nikkibeachmiami/events",
"address": "1 Ocean Dr, Miami Beach"
},
"Nowhere Ftl": {
"url": "https://shotgun.live/venues/nowhere-ftl",
"address": "204 SW 2nd St, Fort Lauderdale"
},
"Ora Nightclub": {
"url": "https://www.facebook.com/oramiami/",
"address": "2000 Collins Ave, Miami Beach"
},
"Playa Wynwood": {
"url": "https://dice.fm/venue/playa-wynwood-2ww5m",
"address": "2125 NW 1st Ct, Miami"
},
"Racket": {
"url": "https://www.facebook.com/racketwynwood/",
"address": "150 NW 24th ST, Miami"
},
"Respectable Street": {
"url": "https://www.facebook.com/respectablestreet/",
"address": "518 Clematis St, West Palm Beach"
},
"Rockwell": {
"url": "https://www.facebook.com/RockwellMiami/events",
"address": "743 Washington Ave, Miami Beach"
},
"Shotimilco": {
"url": "https://www.instagram.com/shotimilco_miami",
"address": "1225 SW 8th St, Miami"
},
"SHOTS Miami": {
"url": "https://www.facebook.com/SHOTSMiami/",
"address": "311 NW 23rd St, Miami"
},
"Stache": {
"url": "https://www.facebook.com/stacheftl/events",
"address": "109 SW 2nd Ave, Fort Lauderdale"
},
"Star Lounge": {
"url": "https://www.facebook.com/starloungefl/",
"address": "115 N 21st Ave, Hollywood"
},
"STK Miami": {
"url": "https://www.facebook.com/stkwmiami/",
"address": "1100 Biscayne Blvd, Miami"
},
"STORY Miami": {
"url": "https://www.facebook.com/storymiami/events",
"address": "136 Collins Ave, Miami Beach"
},
"The Anderson": {
"url": "https://www.facebook.com/theandersonmiami/events",
"address": "709 NE 79th St, Miami"
},
"The Bridge": {
"url": "https://www.facebook.com/TheBridgeMiami/",
"address": "4220 NW 7th Ave, Miami"
},
"The Dirty Rabbit": {
"url": "https://www.facebook.com/thedirtyrabbitwynwood/",
"address": "151 NW 24th St, Miami"
},
"The Hangar": {
"url": "https://www.facebook.com/Thehangar305/",
"address": "60 NE 11th St, Miami"
},
"The Sylvester": {
"url": "https://www.facebook.com/thesylvesterbar/",
"address": "3456 N Miami Ave, Miami"
},
"The Venue Fort Lauderdale": {
"url": "https://www.facebook.com/TheVenueFortLauderdale/",
"address": "2345 Wilton Dr, Fort Lauderdale"
},
"TRADE": {
"url": "https://www.facebook.com/TRADEMIA/events",
"address": "1437 Washington Ave, Miami"
},
"Twist": {
"url": "https://www.facebook.com/twistsouthbeach/",
"address": "1057 Washington Ave, Miami Beach"
},
"Vandal Warehouse": {
"url": "https://www.facebook.com/VandalWarehouse/events",
"address": "1109 Old Okeechobee Rd, West Palm Beach"
},
"Wall Lounge": {
"url": "https://www.facebook.com/wallmiami/events",
"address": "2201 Collins Ave, Miami Beach"
},
"Wynwood Factory": {
"url": "https://www.facebook.com/thewynwoodfactory/",
"address": "55 NE 24th St, Miami"
},
"Yuca": {
"url": "https://www.facebook.com/yucarestaurantandlounge/",
"address": "501 Lincoln Rd, Miami Beach"
},
"THRoW Social": {
"url": "https://www.instagram.com/throwsocialmiami/",
"address": "2335 N Miami Ave, Miami"
}
},
"crews": [
{
"name": "411 Panico",
"url": "https://www.instagram.com/411panico/"
},
{
"name": "Alwayslunes",
"url": "https://shotgun.live/venues/alwayslunes"
},
{
"name": "Ambitious Children",
"url": "https://www.instagram.com/ambitiouschildren/"
},
{
"name": "AmericanGrime",
"url": "https://www.facebook.com/AmericanGrime/"
},
{
"name": "ANNEX Miami",
"url": "https://www.instagram.com/annexmiami"
},
{
"name": "Around the Corner",
"url": "https://www.eventbrite.com/o/around-the-corner-43171428303"
},
{
"name": "Around the Corner IG",
"url": "https://www.instagram.com/atc.miami/"
},
{
"name": "Atrium Productions",
"url": "https://www.facebook.com/atriumproductions/"
},
{
"name": "Audioplayground Entertainment",
"url": "https://www.facebook.com/audioplaygroundent/"
},
{
"name": "Bass Music Society",
"url": "https://shotgun.live/venues/bass-music-society"
},
{
"name": "Bass Stilla",
"url": "https://www.facebook.com/Bass-Stilla-239138619980729/"
},
{
"name": "BassLine Miami",
"url": "https://www.facebook.com/basslinemia/events"
},
{
"name": "Beat Camp",
"url": "https://www.eventbrite.com/o/craze-beat-camp-20007519080"
},
{
"name": "Beat Nation Miami",
"url": "https://shotgun.live/en/venues/beatnationmiami"
},
{
"name": "Black Cat Sound System",
"url": "https://www.facebook.com/blackcatsoundsystems/"
},
{
"name": "BLNK CNVS",
"url": "https://www.tixr.com/groups/blnkcnvs"
},
{
"name": "Breaks Yo",
"url": "https://www.facebook.com/BreaksYo/"
},
{
"name": "Bunker Bliss",
"url": "https://www.instagram.com/bunkerbliss/"
},
{
"name": "Bunker Bliss Shotgun",
"url": "https://shotgun.live/venues/bunker-bliss"
},
{
"name": "Concreta Sala",
"url": "https://shotgun.live/venues/concreta-sala"
},
{
"name": "Culture Productions",
"url": "https://www.facebook.com/culture808/"
},
{
"name": "Daer Dayclub Tixr",
"url": "https://www.tixr.com/groups/daerdayclubsouthflorida"
},
{
"name": "Deep Playa",
"url": "https://www.facebook.com/DeepPlaya"
},
{
"name": "Deep Tech Miami",
"url": "https://www.eventbrite.com/o/deep-tech-miami-44436743943"
},
{
"name": "Deep2Groove",
"url": "https://www.facebook.com/Deep2Groove.MIAMI/"
},
{
"name": "Delta Elite Division",
"url": "https://www.facebook.com/Delta-Elite-Division-453534698345822/"
},
{
"name": "Descent Electronica",
"url": "https://www.facebook.com/DescentElectronica/"
},
{
"name": "DLTA Division",
"url": "https://www.facebook.com/DLTADIVISION/"
},
{
"name": "Do Not Sit On The Furniture ShotgunLive",
"url": "https://shotgun.live/venues/do-not-sit-on-the-furniture"
},
{
"name": "Double-A Entertainment Studios",
"url": "https://www.facebook.com/aaentertainmentstudios/"
},
{
"name": "Dubday",
"url": "https://www.facebook.com/DubdayMIA/"
},
{
"name": "EC Underground",
"url": "https://www.eventbrite.com/o/ec-underground-81275744383"
},
{
"name": "Electric Love Productions",
"url": "https://www.facebook.com/ElectricLoveProductions/"
},
{
"name": "Electronic Groove",
"url": "https://www.facebook.com/electronicgroove"
},
{
"name": "Electronic Hideout",
"url": "https://www.instagram.com/electronichideout"
},
{
"name": "Element",
"url": "https://www.facebook.com/elementmia/"
},
{
"name": "Fader Events",
"url": "https://shotgun.live/venues/fader-events"
},
{
"name": "Fallout Bookings",
"url": "https://www.facebook.com/FalloutBookings/"
},
{
"name": "Florida Rave Fam",
"url": "https://www.facebook.com/FloridaRaveFam/"
},
{
"name": "Footwork",
"url": "https://shotgun.live/venues/footwork"
},
{
"name": "Forward the Motion",
"url": "https://www.facebook.com/forwardthemotion/"
},
{
"name": "From The South Records",
"url": "https://www.facebook.com/FromTheSouthRecords/"
},
{
"name": "Ghost Sound",
"url": "https://shotgun.live/venues/ghost-sound-miami"
},
{
"name": "Hidethebody",
"url": "https://shotgun.live/venues/hidethebody"
},
{
"name": "Home Bass",
"url": "https://www.facebook.com/HomeBass/"
},
{
"name": "House Show",
"url": "https://shotgun.live/venues/house-show"
},
{
"name": "House Show IG",
"url": "https://www.instagram.com/houseshow.fl/"
},
{
"name": "Humans Alike",
"url": "https://www.facebook.com/Humans-Alike-100669656642646/"
},
{
"name": "I Love Florida House",
"url": "https://www.facebook.com/ILoveFloridaHOUSE/"
},
{
"name": "Keep it Deep",
"url": "https://www.facebook.com/groups/KeepItDeepMiami/"
},
{
"name": "KLDSCP Events",
"url": "https://www.instagram.com/kldscpevents/"
},
{
"name": "Kontrol Alt Delete",
"url": "https://shotgun.live/venues/kontrol-alt-delete-productions"
},
{
"name": "KPSPRO",
"url": "https://www.facebook.com/Kpspro/"
},
{
"name": "LASHwynwood",
"url": "https://www.facebook.com/LASHwynwood/events"
},
{
"name": "LINK Miami Rebels",
"url": "https://www.facebook.com/LinkMiamiRebels"
},
{
"name": "Liquid Space Disco Music",
"url": "https://www.facebook.com/LSDMusic19/"
},
{
"name": "LowR Levels",
"url": "https://www.facebook.com/LowrLevls/"
},
{
"name": "Lows Only",
"url": "https://www.facebook.com/LowsOnly/"
},
{
"name": "Lows Only Shotgun",
"url": "https://shotgun.live/venues/lows-only"
},
{
"name": "Lvl Up Events",
"url": "https://www.facebook.com/LvLUpEvnts/"
},
{
"name": "LYTWRK Records",
"url": "https://www.eventbrite.com/o/lytwrk-records-104771183181"
},
{
"name": "Mad Radio Miami",
"url": "https://shotgun.live/venues/mad-radio-miami"
},
{
"name": "Massive Ideas",
"url": "https://www.facebook.com/massiveideas/"
},
{
"name": "Miami Music Week 2024",
"url": "https://www.tixr.com/promoters/Miamimusicweek2024"
},
{
"name": "Miami Spring Break",
"url": "https://www.eventbrite.com/o/miami-spring-break-2024-33476114877"
},
{
"name": "Minimax",
"url": "https://www.facebook.com/minimaxevents/"
},
{
"name": "Monotone",
"url": "https://www.facebook.com/groups/585524438224062/"
},
{
"name": "More or Less",
"url": "https://www.facebook.com/moreorlessmia/"
},
{
"name": "Omni Sounds Events",
"url": "https://shotgun.live/venues/omnisoundsevents"
},
{
"name": "Pass The Good Entertainment",
"url": "https://www.facebook.com/PassTheGoodEntertainment/"
},
{
"name": "Perreo Del Futuro",
"url": "https://shotgun.live/venues/perreo-del-futuro"
},
{
"name": "Planeta Rave",
"url": "https://www.instagram.com/planeta.rave/"
},
{
"name": "PMD",
"url": "https://www.facebook.com/PMDcopro/"
},
{
"name": "Poizd Program",
"url": "https://www.eventbrite.com/o/poizd-program-31699247265"
},
{
"name": "Promised Land Productions",
"url": "https://www.facebook.com/PromisedLandprod/"
},
{
"name": "Proper Etiquette",
"url": "https://www.instagram.com/itsproperetiquette/"
},
{
"name": "Proper Etiquette POSH",
"url": "https://posh.vip/g/events-by-proper-etiquette"
},
{
"name": "RaveMiami",
"url": "https://www.facebook.com/RaveMiamiINC/"
},
{
"name": "Rhythm Foundation",
"url": "https://www.eventbrite.com/o/rhythm-foundation-8435872624"
},
{
"name": "Rhythms Ofc",
"url": "https://www.facebook.com/rhythms.miami/"
},
{
"name": "Romanticos",
"url": "https://www.instagram.com/romanticos_collective/"
},
{
"name": "Running Late",
"url": "https://www.instagram.com/runninglate.events"
},
{
"name": "Scooch305",
"url": "https://www.facebook.com/Scooch305/"
},
{
"name": "Secret Garden",
"url": "https://www.facebook.com/secretgardenexp/"
},
{
"name": "Secto Promoz",
"url": "https://www.facebook.com/SectoPromoz/"
},
{
"name": "SectorX Entertainment",
"url": "https://www.facebook.com/SectorXENT/"
},
{
"name": "Simulation",
"url": "https://www.facebook.com/SimulationEvent/"
},
{
"name": "Slap & Tickle",
"url": "https://www.facebook.com/slapnticklemiami/"
},
{
"name": "Sogood Events",
"url": "https://www.facebook.com/sogoodmusicmedia/"
},
{
"name": "Soundtuary",
"url": "https://www.facebook.com/thesoundtuary/"
},
{
"name": "Spaced Out Entertainment",
"url": "https://www.facebook.com/spacedoutdj/"
},
{
"name": "Stamina",
"url": "https://www.instagram.com/staminafl/"
},
{
"name": "Steph J Khouri",
"url": "https://www.instagram.com/stephjkhouri"
},
{
"name": "Strange Bass",
"url": "https://www.facebook.com/StrangeBassMIA/"
},
{
"name": "Sub-Motus",
"url": "https://www.facebook.com/Sub.Motus/events"
},
{
"name": "Substructure",
"url": "https://www.facebook.com/Subfl/"
},
{
"name": "Subtek",
"url": "https://www.facebook.com/SubtekMovement/"
},
{
"name": "Sunday Sessions",
"url": "https://shotgun.live/venues/sunday-sessions-vinyl-only"
},
{
"name": "Supernatural Haus",
"url": "https://www.instagram.com/supernaturalhaus/"
},
{
"name": "Team Underground",
"url": "https://www.facebook.com/tu.underground/"
},
{
"name": "Team Underground EB",
"url": "https://www.eventbrite.com/o/team-underground-17662185870"
},
{
"name": "Techno Collective",
"url": "https://shotgun.live/venues/techno-collective"
},
{
"name": "THCNO",
"url": "https://www.facebook.com/thcnoevents/"
},
{
"name": "The Boombox Miami",
"url": "https://shotgun.live/venues/the-boombox-miami"
},
{
"name": "The Revera Corporation",
"url": "https://www.facebook.com/reveracorp/"
},
{
"name": "The Trip",
"url": "https://www.instagram.com/the_trip_miami/"
},
{
"name": "Third Eye Hospitality",
"url": "https://linktr.ee/thirdeyehospitalityco/"
},
{
"name": "TOO FUTURE",
"url": "https://www.facebook.com/toofuture/"
},
{
"name": "Treehouse Miami ShotgunLive",
"url": "https://shotgun.live/venues/treehousemiami"
},
{
"name": "Turntable Bagel",
"url": "https://www.instagram.com/turntablebagel"
},
{
"name": "Un_Mute",
"url": "https://www.facebook.com/unmuteevents/"
},
{
"name": "Un_Mute ShotgunLive",
"url": "https://shotgun.live/venues/un-mute"
},
{
"name": "Untitled Rhythms",
"url": "https://shotgun.live/venues/untitled-rhythms"
},
{
"name": "Utopya",
"url": "https://www.facebook.com/utopyamiami/"
},
{
"name": "UVA UVA",
"url": "https://www.instagram.com/uvauvawynwood/"
},
{
"name": "We Love Underground Music",
"url": "https://www.facebook.com/WELOVEUNDREGROUNDMUSIC/"
},
{
"name": "Woke",
"url": "https://www.facebook.com/wokevision/"
}
]
};
