#!/usr/bin/env python3
"""Refresh underground/js/events.js from the 19hz.info South Florida calendar.

  python3 underground/tools/update.py              # fetch live page
  python3 underground/tools/update.py page.html    # parse a saved copy
"""
import html, json, re, sys, urllib.request
from datetime import date
from pathlib import Path

SRC = 'https://19hz.info/eventlisting_Miami.php'
OUT = Path(__file__).resolve().parent.parent / 'js' / 'events.js'


def text(s):
    return html.unescape(re.sub(r'<[^>]+>', ' ', s)).replace('\xa0', ' ').strip()


def split_title(cell):
    """'<a href=u>Title</a> @ Venue (City)' -> (title, url, venue, city)."""
    m = re.search(r"<a href=['\"]([^'\"]+)['\"]>(.*?)</a>", cell, re.S)
    url, title = (m.group(1), text(m.group(2))) if m else ('', '')
    rest = text(cell[m.end():] if m else cell)
    venue, city = rest.lstrip('@ ').strip(), ''
    cm = re.match(r'(.*)\(([^()]*)\)\s*$', venue)
    if cm:
        venue, city = cm.group(1).strip(), cm.group(2).strip()
    return title or text(cell), url, venue, city


def price_age(s):
    s = text(s)
    parts = [p.strip() for p in s.split('|')]
    age = parts[-1] if len(parts) > 1 and re.search(r'\d\d\+', parts[-1]) else ''
    if not age:
        m = re.search(r'\b(18|21)\+', s)
        age = m.group(0) if m else ''
    price = parts[0] if not (len(parts) == 1 and age and parts[0] == age) else ''
    return price, age


def rows(block):
    for tr in re.findall(r'<tr[^>]*>(.*?)</tr>', block, re.S):
        tds = re.split(r'<td[^>]*>', tr)[1:]
        tds = [re.sub(r'</td>\s*$', '', t.strip()) for t in tds]
        if len(tds) >= 5:
            yield tds


def parse(page):
    rec_at = page.find("id='recurring'")
    ven_at = page.find("id='venueList'")
    crew_at = page.find('id="crewList"')
    events, recurring, venues, crews = [], [], {}, []

    for td in rows(page[:rec_at]):
        when = text(td[0])
        tm = re.search(r'\(([^)]*)\)', when)
        iso = text(td[-1]).replace('/', '-')
        if not re.match(r'\d{4}-\d\d-\d\d', iso):
            continue
        title, url, venue, city = split_title(td[1])
        price, age = price_age(td[3])
        events.append({
            'date': iso[:10], 'time': tm.group(1) if tm else '', 'title': title, 'url': url,
            'venue': venue, 'city': city,
            'tags': [t.strip() for t in text(td[2]).split(',') if t.strip()],
            'price': price, 'age': age, 'crew': text(td[4]),
        })

    for td in rows(page[rec_at:ven_at]):
        when = text(td[0])
        title, url, venue, city = split_title(td[1])
        price, age = price_age(td[3])
        recurring.append({
            'when': re.sub(r'\s*\(.*', '', when), 'time': (re.search(r'\(([^)]*)\)', when) or [None, ''])[1],
            'title': title, 'url': url, 'venue': venue, 'city': city,
            'tags': [t.strip() for t in text(td[2]).split(',') if t.strip()],
            'price': price, 'age': age,
        })

    for m in re.finditer(r"<a href=['\"]([^'\"]+)['\"]>(.*?)</a>\s*-\s*([^<]+)", page[ven_at:crew_at]):
        venues[text(m.group(2))] = {'url': m.group(1), 'address': text(m.group(3))}

    for m in re.finditer(r"<a href=['\"]([^'\"]+)['\"]>(.*?)</a>", page[crew_at:]):
        crews.append({'name': text(m.group(2)), 'url': m.group(1)})

    return {'updated': date.today().isoformat(), 'source': SRC,
            'events': events, 'recurring': recurring, 'venues': venues, 'crews': crews}


def main():
    if len(sys.argv) > 1:
        page = Path(sys.argv[1]).read_text(encoding='utf-8')
    else:
        req = urllib.request.Request(SRC, headers={'User-Agent': 'underground-app/1.0'})
        page = urllib.request.urlopen(req, timeout=30).read().decode('utf-8', 'replace')
    data = parse(page)
    if not data['events']:
        sys.exit('No events parsed; page layout may have changed. events.js left untouched.')
    OUT.write_text('/* Generated by tools/update.py from ' + SRC + ' */\nwindow.UG_DATA = '
                   + json.dumps(data, ensure_ascii=False, indent=0) + ';\n', encoding='utf-8')
    print(f"{len(data['events'])} events, {len(data['recurring'])} recurring, "
          f"{len(data['venues'])} venues, {len(data['crews'])} crews -> {OUT}")


if __name__ == '__main__':
    main()
